spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/studylog
    username: studylog
    password: studylog12349876
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 16379
      password: ${REDIS_PASSWORD}

